// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx5HwbLh0kD9OAFfuCZNnEHKgdZvcG9Kc',
    appId: '1:155891576926:web:7230a6b27402a42e3f44cf',
    messagingSenderId: '155891576926',
    projectId: 'fir-remote-config-poc-722cb',
    authDomain: 'fir-remote-config-poc-722cb.firebaseapp.com',
    storageBucket: 'fir-remote-config-poc-722cb.firebasestorage.app',
    measurementId: 'G-9TLTCRTJZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkN9JGe6Q3nI1G2rdJdItq2kc0Li9-pec',
    appId: '1:155891576926:android:db3062a8b2ac1ee73f44cf',
    messagingSenderId: '155891576926',
    projectId: 'fir-remote-config-poc-722cb',
    storageBucket: 'fir-remote-config-poc-722cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrzX0F8vLCx0rf7V13jkb8nQP0k0Cu_OQ',
    appId: '1:155891576926:ios:2b32dbec8772df403f44cf',
    messagingSenderId: '155891576926',
    projectId: 'fir-remote-config-poc-722cb',
    storageBucket: 'fir-remote-config-poc-722cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseRemoteConfigPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrzX0F8vLCx0rf7V13jkb8nQP0k0Cu_OQ',
    appId: '1:155891576926:ios:2b32dbec8772df403f44cf',
    messagingSenderId: '155891576926',
    projectId: 'fir-remote-config-poc-722cb',
    storageBucket: 'fir-remote-config-poc-722cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseRemoteConfigPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx5HwbLh0kD9OAFfuCZNnEHKgdZvcG9Kc',
    appId: '1:155891576926:web:8e3dc5257998640c3f44cf',
    messagingSenderId: '155891576926',
    projectId: 'fir-remote-config-poc-722cb',
    authDomain: 'fir-remote-config-poc-722cb.firebaseapp.com',
    storageBucket: 'fir-remote-config-poc-722cb.firebasestorage.app',
    measurementId: 'G-HEP2KYT5J3',
  );
}
